### ISSUE TITLE
Check data dimensions for ONET + SOC intersection

### ISSUE THREAD

**Issue by jaimish11** [Semicolon-Bros/Skynet#1]

**Comment by bshah4397** [comment]
Okay, upon spending further time on this you can understand what is the issue out here. I found a _couple_ of them - 

- **Data Type Mismatch:** The datatypes of the various dimensions amongst the datasets vary, things that need to be `int` is actually typecasted to `float`. Also, I suspect this inherit `object` data type of most of the string columns can also be an issue while intersection. Check out the _image_ of all the various data types.
<img width="1023" alt="Screen Shot 2020-06-29 at 9 53 04 PM" src="https://user-images.githubusercontent.com/16777720/86074177-6a7f4900-ba53-11ea-9457-ab79b41376ed.png">

- **Occupation Code Mismatch:** The occupation `Code` found as our so-called "primary" key in almost all the datasets works differently for O*NET compared to SOC, Oxford. The decimal points added after the job are indications that a particular job is broken down into subsequent jobs since they have disparate characteristics w.r.t O*NET variables. Check out the image for better understanding about the working of these decimal and normal occupation `Code` in the _image_ below.
<img width="1018" alt="Screen Shot 2020-06-29 at 9 54 46 PM" src="https://user-images.githubusercontent.com/16777720/86074544-322c3a80-ba54-11ea-99e3-b4f72ad79ffe.png"> 
Another interesting fact is that, if we just take the jobs at face value like grouping these same job titles the way they were in the SOC, Oxford datasets then we have a very reduced dataset of  968 - 194 duplicates = 774 O*NET occupation dataset. Check out the _image_ below - 
<img width="1016" alt="Screen Shot 2020-06-29 at 10 01 18 PM" src="https://user-images.githubusercontent.com/16777720/86074948-de6e2100-ba54-11ea-8120-38f7117bfded.png">


> **O*NET Dataset consists of only 774 jobs out of the 1064 jobs in the SOC**

**Comment by bshah4397** [comment]
https://github.com/Semicolon-Bros/Skynet/blob/e540d2ed698bc124edbc5e19826b1154efd834b0/ML/Pre-processing.ipynb#L862
